### ISSUE TITLE
Inline HTML comments are not rendered properly

### ISSUE THREAD

**Issue by uranusjr** [hoedown/hoedown#115]
Tested in both `moar-bugfixes` and `master`.

Non-block-level HTML comments are escaped (and displayed). This

```
A paragraph.

<!-- a comment -->

Another paragraph with <!-- an inline comment -->
```

would be rendered as

```html
<p>A paragraph.</p>

<!-- a comment -->

<p>Another paragraph with &lt;!-- an inline comment --&gt;</p>
```

My guess is that this is inherited from Sundown, since Redcarpet also had the same issue (vmg/redcarpet#268). They had fixed it though.

**Comment by jmendeth** [comment]
New code doesn't present this problem.
