### ISSUE TITLE
Unintuitive results for nested lists indented with one or two spaces

### ISSUE THREAD

**Issue by uranusjr** [hoedown/hoedown#117]
From uranusjr/macdown#148.

This 
```
* Foo
  * Bar
    * Baz
```

becomes

```
<ul>
<li>Foo
  <ul>
    <li>Bar</li>
    <li>Baz</li>
  </ul>
</li>
</ul>
```

in which **Bar** and **Baz** are on the same level. I would expect

```
<ul>
<li>Foo
  <ul>
    <li>Bar
      <ul>
        <li>Baz</li>
      </ul>
    </li>
  </ul>
</li>
</ul>
```

instead. Same result if I “indent” with only one space. I though this is because the indentation is less than 4 spaces, but I can get the expected result with just 3. Not sure whether this be qualified as invalid input, or considered a bug.

**Comment by jmendeth** [comment]
New code supports this just fine.

**Comment by FranklinYu** [comment]
Current master branch:

``` text
$ cat test.markdown
* Foo
  * Bar
    * Baz
$ cat test.markdown | ./hoedown
<ul>
<li>Foo

<ul>
<li>Bar</li>
<li>Baz</li>
</ul></li>
</ul>
```

The behavior is reverted?
