### ISSUE TITLE
Fenced code blocks are not recognized when first element inside list element

### ISSUE THREAD

**Issue by MarkLodato** [hoedown/hoedown#131]
Example:

    1. ```
       x
       ```

    2. ```
       y
       ```

This should output two `<pre><code>` blocks, as in the following (from [stmd](https://github.com/jgm/stmd)):

```html
<ol>
<li><pre><code>x
</code></pre></li>
<li><pre><code>y
</code></pre></li>
</ol>
```

but instead outputs

```html
<ol>
<li><code>
x
</code></li>
</ol>

<ol>
<li><code>
y
</code></li>
</ol>
```

This is wrong for two reasons:

1. It is should not close and reopen the `<ol>` tag.
2. It should be a `<pre><code>`, not just a normal `<code>`.

**Comment by jmendeth** [comment]
New code does not present the issue.
