### ISSUE TITLE
Allow spaces in fenced code attribute

### ISSUE THREAD

**Issue by uranusjr** [hoedown/hoedown#132]
Currently things after the first space in the fenced code attribute is ignored, so this

    ```foo bar
    lorem ipsum
    ```

is transformed into

```html
<pre><code class="language-foo">lorem ipsum
</code></pre>
```

While this is fine for “standard” syntax (a la CommonMark, GFM, etc.), the approach makes it impossible to extend the syntax without modifying the parser.

I propose that instead of just parsing until the first space, the `lang` attribute should contain all content from the last opening tick/wave to the next newline. For the above example, this means that `lang` will become `foo bar` instead of just `foo`. The HTML render can then do either of the followings:

1. Output it verbatim (with a `language-` prefix)

    ```html
    <pre><code class="language-foo bar">lorem ipsum
    </code></pre>
    ```

2. Split the attribute with space, and prefix each of the items with `language-` (doesn’t make sense to me)

    ```html
    <pre><code class="language-foo language-bar">lorem ipsum
    </code></pre>
    ```

3. Output up to the first space, discard the rest. This makes the output identical as before.

The benefit for this is that custom renderers can treat those extra content anyway they like. This would make it possible to implement, for example, a file name header above the code block, i.e. render this

    ```python hello.py
    print('Hello!')
    ```

into something like

```html
<pre>
  <div class="snippet-filename">hello.py</div>
  <code class="language-python">print 'Hello!'
  </code>
</pre>
```

**Comment by jmendeth** [comment]
As said, new code allows clients to get the full info string.
