### ISSUE TITLE
Unexpected result mixing <em> and <code>

### ISSUE THREAD

**Issue by uranusjr** [hoedown/hoedown#138]
Originally reported at uranusjr/macdown#195

Minimal example:

    _foo `_bar`

Expected:

    <p>_foo <code>_bar</code></p>

Got:

    <p><em>foo `</em>bar`</p>

This is not really a bug, since the original specification does not discuss how ambiguous situations like this should be resolved. But Markdown is designed to be also easily understood verbatim, and the current result is very unintuitive. And [almost all implementations yield the expected result](http://johnmacfarlane.net/babelmark2/?normalize=1&text=_foo+%60_bar%60), including CommonMark.

**Comment by jmendeth** [comment]
New code works as expected.
