### ISSUE TITLE
Smartypants escapes comment tags if the comment body contains angled brackets

### ISSUE THREAD

**Issue by uranusjr** [hoedown/hoedown#143]
Test case:

```html
<!-- bar <baz> -->
```

Output:

```html
<!-- bar <baz> &ndash;>
```

Expected:

```html
<!-- bar <baz> -->
```

(Originally reported at uranusjr/macdown#188.)

**Comment by jmendeth** [comment]
Hey! Why don't we just implement Smartypants as an inline extension only? We don't need a separate executable, it's all in the parser:

    $ hoedown --smartypants < my.markdown

What if you want to process plain text (not Markdown) with Smartypants? Just disable all features except Smartypants:

    $ hoedown --inline --none --smartypants   <<< 'Some *text* ---with smart punctuation---.'
    Some *text* ―with smart punctuation―.

What if you don't have plain text, but HTML, and you'd like your tags and comments to be preserved? Also enable HTML parsing:

    $ hoedown --inline --none --smartypants --html   <<< '<a href="page--v2.html">The article...</a>'
    <a href="page--v2.html">The article…</a>

Looks neat through the API too (remember this is v4 API):

~~~ c
rend = hoedown_html_renderer_new();
doc = hoedown_document_new(rend, HOEDOWN_FT_SMARTYPANTS, 1);

ob = hoedown_document_render(doc, "Some *text* ---with smart punctuation---.", 41, 1);
fwrite(ob->data, ob->size, 1, stdout);
~~~

**Comment by uranusjr** [comment]
Looks nice, but how would the `--html` flag work then? Does it work with all situations, or only make sense with `--smartypants`?

IMHO if this is going to be merged into `libhoedown`, it would be better to make it agnostic to the output language like the rest of it. HTML smartypants-ing (is this a word?) can be standalone like the current one, reusing only minimal components (and move `hoedown_html_smartypants` out of `libhoedown`).

**Comment by jmendeth** [comment]
Okay, context: In my v4 Hoedown, you can disable / enable every feature, individually. These are the different feature flags:

~~~
Block construct features (--all-block):
      --directive        Parse generic directive syntax.
      --indented-code-block  Parse indented code blocks. [CommonMark] [Markdown]
      --fenced-code-block  Parse fenced code blocks. [CommonMark]
      --horizontal-rule  Parse horizontal rules. [CommonMark] [Markdown]
      --atx-header       Parse ATX headers. [CommonMark] [Markdown]
      --setext-header    Parse Setext headers [CommonMark] [Markdown]
      --list             Parse bullet and numbered lists. [CommonMark] [Markdown]
      --quote-block      Parse email-style quote blocks. [CommonMark] [Markdown]
      --html-block       Parse raw HTML blocks. [CommonMark] [Markdown]
      --table            Parse Kramdown style tables.

Inline construct features (--all-inline):
      --role             Parse generic role syntax.
      --escape           Parse backslash escapes. [CommonMark] [Markdown]
      --hard-linebreak   Parse backslash linebreaks. [CommonMark]
      --linebreak        Parse two-space linebreaks. [CommonMark] [Markdown]
      --soft-linebreak   Parse newlines as linebreaks.
      --uri-autolink     Parse URI autolinks between angle brackets. [CommonMark] [Markdown]
      --email-autolink   Parse email autolinks between angle brackets. [CommonMark] [Markdown]
      --html             Parse inline HTML. [CommonMark] [Markdown]
      --entity           Parse HTML entities. [CommonMark] [Markdown]
      --code-span        Parse code spans between backticks. [CommonMark] [Markdown]
      --emphasis         Parse emphasis and strong emphasis. [CommonMark] [Markdown]
      --link             Parse links and link references. [CommonMark] [Markdown]
      --math             Parse Kramdown-style math spans.
      --superscript      Parse superscript spans.
      --quote            Parse quote-delimited spans.
      --strikethrough    Parse strikethrough spans.
      --highlight        Parse highlight spans.
      --footnote         Parse footnotes and footnote references.

Other features (--all-other):
      --preprocess       Preprocess the input. Hoedown can give bad results if input is not preprocessed. [CommonMark] [Markdown]

Feature flags (--all-flags):
      --link-image       Allow links preceded by a bang to be rendered as images. [CommonMark] [Markdown]
      --intra-emphasis   Requires --emphasis. Allow underscores between words to be parsed as emphasis. [Markdown]
      --math-explicit    Requires --math. Enables parsing $...$ as inline math and restricts $$...$$ to block math.
~~~

So you can say "Disable all features!" and then Hoedown turns into a dumb text processor, only recognizing text. Or you could enable just a few, say, preprocessing + emphasis + horizontal rules, and then only those will ever be parsed from your input.

My point is: what if we added `--smartypants` as one of the features? Okay, it's an extension, but if you want plain SmartyPants without Markdown processing, just disable all the other features and the parser turns into a SmartyPanter.

**Comment by jmendeth** [comment]
As you can see, `--html` tells Hoedown to detect and treat the HTML specially, letting it pass untouched. It was there from day zero, since it's essential for Markdown, just as emphasis.

**Comment by jmendeth** [comment]
To demonstrate, I just implemented `HOEDOWN_FT_TYPOGRAPHY`, which is like SmartyPants but it also translates `(c)` to ©. Try to apply it alone to the license:

    hoedown --inline --none --typography LICENSE

You'll get the exact same text in the `LICENSE` with the typographic substitutions applied.
