### ISSUE TITLE
smartypants single trailing squote

### ISSUE THREAD

**Issue by blaenk** [hoedown/hoedown#156]
Smartypants currently doesn't convert the apostrophe in `the computers' keyboards` to an squote. I'd love it if this were fixed :)

**Comment by jmendeth** [comment]
We currently don't accept new features in the v3 (current) codebase.

The development codebase (v4) renders `the computers' keyboards` as `the computers’ keyboards`, which seems to be what you want. Just enable `--typography`. (Corrected a small bug recently)

It leaves internal quotes untouched, so `John's keyboard` currently renders without changes. We can change this easily.

**Comment by blaenk** [comment]
Haha, so v4 has it the other way around? Yeah I think we should fix that too. Sweet :)

**Comment by jmendeth** [comment]
The typography extension is less agressive than SmartyPants, yeah.
