### ISSUE TITLE
Possible to not treat inline math as "normal text"?

### ISSUE THREAD

**Issue by cryptarch** [hoedown/hoedown#161]
Hey there,

I've been working on a LaTeX renderer for hoedown (cryptarch/mdtex) and I'm wondering if it is possible to not treat inline math as "normal text", or whether this could be implemented?

The problem is I would like to convert single dashes between numbers to a LaTeX-style en-dash ("--"). However, when I try doing the replacement, it also replaces minus-signs in inline math. The replacement doesn't happen in displaymode math, which the parser correctly distinguishes from normal text.

I could possibly work around the problem by manually reparsing all normal text to ignore math mode. However, this strikes me as a bit "hacky". With separation of concerns in mind, it would be ideal if distinguishing inline math from normal text were handled by the parser, not the renderer.

Do you see a way towards a good solution for this problem?

**Comment by jmendeth** [comment]
It's already implemented, read on.

The renderer simply implements the `math` callback, which gets passed:

 1. The raw contents of the math span (excluding the delimiters).
 2. A boolean indicating wether a block or inline math span should be rendered.

Then you enable the `--math` extension. Your Markdown can contain math spans of the form `$$math$$`. Hoedown will automatically determine wether the math span is block or inline. Examples:

    This will be a block math span, because it takes the whole paragraph:

    $$a = \frac{1}{b}$$

    This will be an inline math span: $$a = \frac{1}{b}$$

    If you want to be explicit, you can use LaTeX syntax: \\(inline math span\\) and \\[block math span\\].

However, if you'd like to write math spans enclosed by a single dollar, you can enable `--math-explicit` too. Doing this also disables auto-detection; `$$math$$` will always be block math, and `$math$` will always be inline math.

Whatever flags you enable, the renderer implementation should be the same.

**Comment by cryptarch** [comment]
I see. This is very helpful. Thanks very much :-)

**Comment by jmendeth** [comment]
Glad it helped.
