### ISSUE TITLE
Footnote definitions don't support indenting?

### ISSUE THREAD

**Issue by ludovicchabant** [hoedown/hoedown#166]
You can indent the definition of a link, like so:

```
This is a [link][1]

  [1]: http://foo.com
```

But this doesn't seem to work:

```
This footnote[^1] doesn't work.

  [^1]: Nope, it doesn't.
```

I'm not sure if it's *supposed* to work though, since this is not quite standard.

**Comment by ludovicchabant** [comment]
Additionally, they *have* to appear *after* link definitions if link definitions are indented. If you have footnote definitions immediately preceding indented link definitions (even with a couple of blank lines in between), the link definitions don't work anymore.

**Comment by jmendeth** [comment]
Sorry for taking so long to answer. What version of Hoedown are you using? It doesn't seem to happen with the latest version:

~~~ html
<p>This footnote<sup id="fnref1"><a href="#fn1" rel="footnote">1</a></sup> doesn&#39;t work.</p>

<div class="footnotes">
<hr>
<ol>

<li id="fn1">
<p>Nope, it doesn&#39;t.&nbsp;<a href="#fnref1" rev="footnote">&#8617;</a></p>
</li>

</ol>
</div>
~~~

**Comment by jmendeth** [comment]
> Additionally, they have to appear after link definitions if link definitions are indented. If you have footnote definitions immediately preceding indented link definitions (even with a couple of blank lines in between), the link definitions don't work anymore.

I've tried lightly, but I can't reproduce this either.

**Comment by ludovicchabant** [comment]
Ah I may be using an outdated version indeed. I'm using some python bindings, like Hoep and Python-Hoedown, and I think they haven't updated the Hoedown source for more than a year! I'll see if I can patch either of those with a newer version, sorry about that.

(btw, is there any preferred Python package for Hoedown?)

**Comment by jmendeth** [comment]
No problem.

Hmm, bad luck, both packages are using version 2 of Hoedown, it won't be easy to upgrade them to v3...

**Comment by uranusjr** [comment]
I personally think Hoep is slightly better, if you must choose between those two. More customisable, and the API feels more Pythonic. But my favourite Python library for Markdown is [Mistune]. It is pure Python (speedup available with Cython), and with proper customisation its output can be almost identical to Hoedown’s.

[Mistune]: https://github.com/lepture/mistune

**Comment by ludovicchabant** [comment]
Yeah I tried mistune, already, but thanks (I'm currently evaluating a few different Markdown libraries for [PieCrust](http://bolt80.com/piecrust)).

**Comment by jmendeth** [comment]
For products like PieCrust I *strongly* recommend you pick a CommonMark one. If your Markdown is parsed in a standard way, you can switch parsers later without worrying about weird syntax issues popping up.

If you're fine with pure CommonMark syntax (Markdown + fenced code blocks) I'd definitively use CMark, it's fast and maintained. If you need extensions right now, I'd go for Mistune, even though it's not CommonMark.

**Comment by jmendeth** [comment]
In case you're interested, Hoedown v4 is even faster than CMark, it'll have more extensions than the current version and will implement CommonMark. It's still in development, but already usable (some extensions missing). You can find it in the `develop` branch.

**Comment by ludovicchabant** [comment]
Cool, thanks for the info!
