### ISSUE TITLE
unknown option: -soname on Mac OS X

### ISSUE THREAD

**Issue by pacahon** [hoedown/hoedown#167]
When run `make` I get an error:
```
cc -Wl,-soname,libhoedown.so.3 -shared src/autolink.o src/buffer.o src/document.o src/escape.o src/html.o src/html_blocks.o src/html_smartypants.o src/stack.o src/version.o  -o libhoedown.so.3
ld: unknown option: -soname
```
After replacing it with `install_name` I get only 2 warnings:
```
bin/hoedown.c:446:10: warning: comparison of integers of different signs: 'clock_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                if (t1 == -1 || t2 == -1) {
                    ~~ ^  ~~
bin/hoedown.c:446:22: warning: comparison of integers of different signs: 'clock_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                if (t1 == -1 || t2 == -1) {
```
Mb should add it to README?

**Comment by jmendeth** [comment]
Ah, OS X... yeah, we'd need to replace `soname` with `install_name`, use `.dylib` and add `-current_version` and `-compatibility_version` to follow OS X conventions. (This is one of the times you'd want to be using CMake...)

Looks like the easiest solution would be to create a makefile for OS X... @devinus WDYT?

As for the warnings, it's okay, I just forgot to cast that `-1`, I'll do that now.

**Comment by jmendeth** [comment]
@devinus Just a conditional? Wouldn't we need a different target for the dylib? Also the install target changes?
