### ISSUE TITLE
Is EXT_LAX_SPACING really legacy?

### ISSUE THREAD

**Issue by pacahon** [hoedown/hoedown#168]
Hello. I try to emulate GFM with extensions. Example:
```
Sentence line:
* list1
* list2
* list3
```
Many people expected to see list in that case. Is it possible to emulate or restore EXT_LAX_SPACING with partial support? For example, for situation above.

**Comment by jmendeth** [comment]
Hmm, no, that is not possible. `LAX_SPACING` was hackish, it caused bugs thus it was removed.

Version 4 (in development) is CommonMark-compliant and behaves as you want, though.

**Comment by pacahon** [comment]
Thanks for reply. Any idea when alpha can be available?

**Comment by jmendeth** [comment]
It's a matter of months before the basic features are present, I can't be more precise.
