### ISSUE TITLE
Pipe character in tables works incorrectly inside code blocks

### ISSUE THREAD

**Issue by mdinger** [hoedown/hoedown#169]
Both of these examples should look like the original when rendered as a table but neither do.

This:
```
Test  | Table
------|-------------
t = b | `x | y | z`
```

Results in:

```
Test  | Table
------|-------------
t = b | `x
```

This:

```
Test  | Table
------|-------------
t = b | `x \| y \| z`
```

Results in:

```
Test  | Table
------|-------------
t = b | `x \
```

This is basically a clone of https://github.com/rust-lang/rust/issues/28251 sent upstream
cc @Eljay

**Comment by jmendeth** [comment]
Thanks for reporting!
Fixed in f1dba7df2b3075e00cea047a7a2ca96bc43d8255, version 3.0.5 released.

**Comment by mdinger** [comment]
Thanks for the quick turnaround!

**Comment by jmendeth** [comment]
You're welcome! That was an easy one, kind of surprised it'd stayed years until today without any of us noticing (it affected links, emphasis, images...).

**Comment by jmendeth** [comment]
Mentioning @robin580 since this seems to affect Recarpet as well, try with i.e.:

    [some `code]() here`

**Comment by jmendeth** [comment]
@robin850 (same fix should apply)

**Comment by robin850** [comment]
@jmendeth : hey, thank you very much ; I will have a look at it ! :-)
