### ISSUE TITLE
New paragraph/list items not distinguished correctly

### ISSUE THREAD

**Issue by adob** [hoedown/hoedown#183]
In long documents, it sometimes desirable to indent body text to distinguish it from headings. Here is an example:

```markdown
## Heading

   Paragraph 1.

   1.  Item 1 line 1.
       Item 1 line 2.

   2.  Item 2 line 1.
       Item 2 line 2.

   Paragraph 2.
```

The bug is that hoedown thinks that "Paragrpah 2" is part of Item 2 and generates the following HTML:

```HTML
<h2>Heading</h2>

<p>Paragraph 1.</p>

<ol>
<li><p>Item 1 line 1.
   Item 1 line 2.</p></li>
<li><p>Item 2 line 1.
   Item 2 line 2.</p>

<p>Paragraph 2.</p></li>
</ol>
```

The CommonMark spec gets this right. See http://spec.commonmark.org/0.7/#list-item and [this](http://spec.commonmark.org/dingus/?text=%23%23%20Heading%0A%0A%20%20%20Paragraph%201.%0A%0A%20%20%201.%20%20Item%201%20line%201.%0A%20%20%20%20%20%20%20Item%201%20line%202.%0A%0A%20%20%202.%20%20Item%202%20line%201.%0A%20%20%20%20%20%20%20Item%202%20line%202.%0A%0A%20%20%20Paragraph%202.%0A) example.

**Comment by jmendeth** [comment]
These are implications of the four-space rule.
The stable Hoedown codebase (version 3) is *not* CommonMark compliant.

The development version (see `develop` branch) does target CommonMark compliance, and behaves as expected:

~~~ html
<h2>Heading</h2>
<p>Paragraph 1.</p>
<ol>
<li>
<p>Item 1 line 1.
Item 1 line 2.</p>
</li>
<li>
<p>Item 2 line 1.
Item 2 line 2.</p>
</li>
</ol>
<p>Paragraph 2.</p>
~~~

Therefore, I'm closing this.

**Comment by jmendeth** [comment]
Clarification, JIC: The stable version does not accept changes or issues unless it's for bugfixes. All development is focused on version 4, even though it's currently stalled on source mapping...
