### ISSUE TITLE
Is it possible to render list inside paragraph?

### ISSUE THREAD

**Issue by pacahon** [hoedown/hoedown#204]
Hello. Many markdown parsers convert this text:
```
text
* option1
* option2
```
to html:
```
<p>text</p>
<ul>
<li>option1</li>
<li>option2</li>
</ul>
```

Is it possible to render list with hoedown too? Now hoedown output looks like:
```
<p>text
* option1
* option2</p>
```

Am I missed some flag or it's just not allowed by markdown specification?

**Comment by Jmuccigr** [comment]
From Gruber's spec: `A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines.` So no blank line, no new paragraph and therefore the asterisks aren't read as list markers.

**Comment by pacahon** [comment]
@Jmuccigr Thanks for response! CommonMark specification is more user-friendly in that way, it's a pity, that dev branch was abandoned.
