### ISSUE TITLE
List depth > 5 not shown

### ISSUE THREAD

**Issue by motey** [hoedown/hoedown#210]
Tested with: QOwnNotes Notepad Version version 17.02.1 - AppVeyor - build 2787 using hoedown @ Windows 10
_Sorry, atm i haven't got the time to build up a hoedown testbed. Author of QOwnNotes thinks its an howdown issue. See: #https://github.com/pbek/QOwnNotes/issues/473
If i find the time next week, i try to confirm this issue with hoedown directly, if nobody else does until then._
 
**How to reproduce:**
make a list with 8 bulletpoints and make every following point a child of previous point by tab indent 
_* \t -> tabulator_
```
* 1
\t* 2
\t\t* 3
\t\t\t* 4
\t\t\t\t* 5
\t\t\t\t\t* 6
\t\t\t\t\t\t* 7
\t\t\t\t\t\t\t* 8
```

Expected Result in render view:
```
• 1 
    • 2 
        • 3 
            • 4 
                • 5 
                    • 6 
                        • 7 
                            • 8 
```
Actual result:
```
• 1 
    • 2 
        • 3 
             • 4 
                 • 5 
```

**Comment by uranusjr** [comment]
This is a QOwnNotes issue. Hoedown allows the caller to specify a `max_nesting` that limits HTML tags to a certain level. [QOwnNotes sets this to 16](https://github.com/pbek/QOwnNotes/blob/3c4349b1a5d4eeca63242e811e6a2f7e8995499a/src/entities/note.cpp#L1325). You’ll need to ask QOwnNotes’s maintainers to increase this to support more levels of tag nesting.

**Comment by pbek** [comment]
Thank you for clearing that up, @uranusjr!
