### ISSUE TITLE
Markdown AST inquiry

### ISSUE THREAD

**Issue by zdne** [hoedown/hoedown#22]
Gentlemen, 
   first let allow me thank you for your effort with `Hoedown`. What you have done so far is truly remarkable!

I am running my own fork of `Sundown` that extends it in two major ways:

1. Adds [three additional "rendering" hooks](https://github.com/apiaryio/sundown/blob/master/src/markdown.h#L102) to allow me build parsed Markdown abstract syntax tree (AST) instead of rendering 

2. Adds [source maps](https://github.com/apiaryio/sundown/blob/master/src/src_map.h) so you can tell where in the Markdown source document the block being renders comes from

This two "extensions" allow me to build the Markdown AST in memory so it can be processed later by some other tools (e.g. the [API Blueprint Parser](https://github.com/apiaryio/snowcrash) in my case).

My question is: **Would you care about such a contribution to the `Hoedown` project so it can be used to build Markdown ASTs?**

If so, should `Hoedown` just support building Markdown ASTs thanks to sufficient hooks and source maps or should it also offer a full AST on its own?

Thank you for consideration.

**Comment by jmendeth** [comment]
AST support [alive and kicking!](https://cloud.githubusercontent.com/assets/1177304/5606914/54a3d99a-9446-11e4-8d88-d1cb57e51452.png) In this case, the AST is converted to JSON and prettyprinted.

**Comment by jmendeth** [comment]
Note, it uses the CommonMark rewrite branch which is still in my repo, but will soon be pushed to here.

**Comment by jmendeth** [comment]
Works [with block nesting](https://cloud.githubusercontent.com/assets/1177304/5607039/c80a82dc-9449-11e4-9ac9-e100bd7ef885.png) et all.

**Comment by jmendeth** [comment]
The new code has been pushed here, closing this.

**Comment by zdne** [comment]
:+1:

**Comment by RuiAAPeres** [comment]
@zdne @jmendeth 

> The new code has been pushed here, closing this.

Where?
