### ISSUE TITLE
Source maps in Hoedown

### ISSUE THREAD

**Issue by mildsunrise** [hoedown/hoedown#28]
<sup>Derived from #22.</sup>

The renderers should be given the position of the block they're rendering.
An easy and low-level way to do that would be to pass a `size_t pos` as
last argument to the callbacks where possible, indicating the position of
the block in the input buffer.

That would however make callbacks longer and most of the time this
feature isn't gonna be used.

**Comment by jmendeth** [comment]
Source mapping like the one discussed here (non-contiguous ranges) is coming soon.

I've used it to highlight the [CommonMark spec](http://jmendeth.com/random/2015-04-09-hoedown-highlight/spec.md.html) and [Hoedown's README](http://jmendeth.com/random/2015-04-09-hoedown-highlight/README.md.html) as a demo. Hover to see the tree path of what's under the cursor!

I'll soon make a proposal PR to see what you guys think of the API.

**Comment by zdne** [comment]
:+1:

**Comment by blaenk** [comment]
awesome
